version: "1"

# Issue Welcome
# comments a certain string when an issue is created
issuewelcome:
  enabled: false
  message: >
         Welcome to our github repository and thank you for creating that issue!
# label manager
# lets users add labels to their own issues:
# p!label-add label
# p!label-remove label
labelmanager:
  enabled: true

# Checks issues for a regex
# Useful for making sure noobs fill the issue template correctly
regexIssueChecks:
  enabled: true
  # the regexes
  regexes:
    - "this is"
  # comment sent if its successfull, comment out to disable
  successMessage: >
                   Thank you for filling in the template correctly
