version: "1"

# Issue Welcome
# comments a certain string when an issue is created
issuewelcome:
  enabled: true
  message: >
         Welcome to our github repository and thank you for creating that issue!
labeladd:
  enabled: true
