version: "1"

# Issue Welcome
# comments a certain string when an issue is created
issuewelcome:
  enabled: false
  message: >
         Welcome to our github repository and thank you for creating that issue!
# label manager
# lets users add labels to their own issues:
# p!label-add label
# p!label-remove label
labelmanager:
  enabled: true

# Checks issues for a regex
# Useful for making sure noobs fill the issue template correctly
regexIssueChecks:
  # if you want to disable any messages/labels comment the field out
  enabled: true
  # the regexes
  regexes:
    - "this is"
  # comment sent if its successfull
  successMessage: >
   Thank you for filling in the template correctly
  # Labels to add if it succeeds
  successLabels:
    - valid
    
  # Should the issue
  reopenOnSuccess: true
  
  # comment sent if failed
  failMessage: >
   You did not fill up the issue template
   Regexes didnt match
  # Labels to add if it fails
  failLabels:
    - invalid
    
  closeOnFail: true
  
